# Site settings
title: Blog of my academic life
email: dr.lilongyuan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Life is short, have a blog site.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: lly930514
github_username:  DragonCircle

# Layout settings
header_type: default  # values [ drawer, default ]
post_type: highlight    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]

more_vert:
  option1:
    name: Cool Option 1
    link: www.myawesomelink.com
  option2:
    name: Cool Option 2
    link: www.myawesomelink.com
  option3:
    name: Cool Option 3
    link: www.myawesomelink.com

# Build settings
markdown: kramdown
